POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Janie",
    "email": "janie@j.com"
}

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "25f47afc-ab35-4148-b63c-864f2c981787"
}

###
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
    "account_id_to": "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    "amount": 50.0
}