POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Janie",
    "email": "janie@j.com"
}

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "18c376b4-d566-4dab-a7b1-d4d782f8137b"
}

###
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    "account_id_to": "5f088b3a-bbfb-4eed-8321-38625b11e925",
    "amount": 100.0
}